baseurl = "https://temme.cloud/"
title = "Temme Cloud & Tech GmbH"
theme = "hugo-universal-theme"
themesDir = "../.."
languageCode = "de-DE"
defaultContentLanguage = "de"
summaryLength = 70
pluralizelisttitles = false

[services]
    [services.disqus]
        shortname = ""
    [services.googleAnalytics]
        id = ""

[pagination]
    pagerSize = 10

[menu]
[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "About Us"
    identifier = "menu.about"
    url        = "/about/"
    weight     = 2

[[menu.main]]
    name       = "Services"
    identifier = "menu.services"
    url        = "/services/"
    weight     = 3

[[menu.main]]
    name       = "Portfolio"
    identifier = "menu.portfolio"
    url        = "/portfolio/"
    weight     = 4

[[menu.main]]
    name       = "Blog"
    identifier = "menu.blog"
    url        = "/blog/"
    weight     = 5

[[menu.main]]
    name       = "Contact"
    identifier = "menu.contact"
    url        = "/contact/"
    weight     = 6

[[menu.topbar]]
    weight = 1
    name = "Phone"
    url = "tel:+49 123 456 789"
    pre = "<i class='fas fa-2x fa-phone'></i>"

[[menu.topbar]]
    weight = 2
    name = "GitHub"
    url = "https://github.com/temme.cloud"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 3
    name = "Email"
    url = "mailto:info@temme.cloud"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[params]
    author = "Temme Cloud & Tech GmbH"
    defaultKeywords = ["IT-Dienstleistungen", "Softwareentwicklung", "Cloud-Computing"]
    defaultDescription = "Temme Cloud & Tech GmbH - IT-Dienstleistungen und Softwareentwicklung"
    style = "custom.css"
    logo = "logo.png"
    # logo_small = "img/logo-small.png"
    contact_url = "/contact"
    address = """<p><strong>Temme Cloud & Tech GmbH</strong><br>Grüntaler Str. 32<br>Berlin, Germany</p>"""
    copyright = "Copyright © 2025 Temme Cloud & Tech GmbH. All rights reserved."
    enableGoogleMaps = false
    dropdown_mouse_over = false
    disabled_logo = false

# [params.topbar]
#     enable = true
#     text = """<p>Contact us at +49 123 456 789 or info@temme.cloud.</p>"""

[params.widgets]
    categories = true
    tags = true
    search = true

[params.carouselHomepage]
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.features]
    enable = true
    cols = 3

# [params.testimonials]
#     enable = true
#     title = "Testimonials"
#     subtitle = "What our clients say about us."

# [params.recent_posts]
#     enable = true
#     title = "From our blog"
#     subtitle = "Latest updates and insights from our team."
#     hide_summary = false

# [params.footer.recent_posts]
#     enable = true

[taxonomies]
    category = "categories"
    tag = "tags"
    author = "authors"
