baseURL = 'https://temme.cloud/'
language = 'de'
languageCode = 'de-DE'
title = 'Temme Cloud & Tech GmbH'
subtitle = 'IT-Dienstleistungen und Softwareentwicklung'
theme = 'hello-friend-ng'
contentDir = "content"

[params]
author = "Temme Cloud & Tech GmbH"
dateform = "2. Jan 2006"
dateformShort = "2. Jan"
dateformNum = "02.01.2006"
dateformNumTime = "02.01.2006 15:04"

# Subtitle for home
homeSubtitle = "Hier entsteht gerade etwas Neues."

# Set disableReadOtherPosts to true in order to hide the links to other posts.
disableReadOtherPosts = true

# Enable sharing buttons, if you like
enableSharingButtons = false

# Show a global language switcher in the navigation bar
enableGlobalLanguageMenu = false

# Metadata mostly used in document's head
description = "Temme Cloud & Tech GmbH - IT-Dienstleistungen und Softwareentwicklung"
keywords = "Temme Cloud & Tech GmbH, IT-Dienstleistungen, Softwareentwicklung, DevOps, Backend, Software, Freelancer, Golang, Python, TypeScript, HTML, CSS, Webentwicklung, Cloud-Computing, Kubernetes, Docker, Terraform, Ansible, CI/CD, Continuous Integration, Continuous Deployment, Agile Softwareentwicklung, GitLab, GitHub, Jira, Confluence, Scrum, Kanban, IT-Sicherheit, Datenschutz, DSGVO, IT-Consulting, IT-Architektur, IT-Strategie, IT-Projektmanagement"
# Set the default image for the og:image meta tag
images = [""]

defaultContentLanguage = 'de'

[params.logo]
path = "/logo.svg"
alt = "Logo"
# logoText = "in development :)"
# logoHomeLink = "/"

[params.footer]
bottomText = [
    "<a href=\"/impressum\">Impressum</a>",
    "<a href=\"/datenschutz\">Datenschutz</a>",
]

[params.meta]
favicon = true
